### PR TITLE
ansible-lint: Linter

### PR DESCRIPTION
**Pull request by Rendanic**
This PR added all changes to make the project compatible with ansible-lint.
It is not completed yet...

### CODE REVIEW

**Comment by godspeed-you** [comment]
Thanks for the effort to lint all these lines. I have just one problem with that and a suggestion: The commit does not change the functionality at all, but masquerades the functional changes behind linting commits. 

I would rather suggest implementing a minimal approach (e.g. skip all the indention changes) and keep the commit history as clean as possible. This helps to identify bugs as fast as possible. The indention will then be changed/linted only if the affected lines are needed to be changed for contentual reasons.

**Comment by godspeed-you** [comment]
One more thing that needs to be evaluated: We want to be compatible to older Ansible versions as long as this is possible (and reasonable). I suspect some of your changes to be compatible with only newer versions of Ansible. Please assure that your changes are as compatible with older versions as possible.

**Comment by Rendanic** [comment]
I'll stop the work on this PR due to missing time..
I started using ansible-lint a couple of weeks ago and it is a fantastic tool. You should test it and clean all warnings. 

My oldest version is 2.9, because that release is the 1st one with full collection support. Xou should check that  feauture. It brings Ansible to real new level of developing roles. The incompatible changes to old versions are worth the change and 2.9 is currently the oldest full supported version of Ansible at the moment.


Greetings
Thorsten

**Comment by Rendanic** [comment]
I stopped working on this.

=> Closing PR

**Pull request closed without merging**
